### PR TITLE
Create tr.yml

### PR DESCRIPTION
**Pull request by tolgaaaltas**
Turkish language support for this extension.

### CODE REVIEW

**Comment by datitisev** [comment]
Hey @tolgaaaltas.

Thanks for the multiple PRs to our extensions. Sadly, we won't be merging them as we've decided to only maintain English locale and leave other languages to language packs (you can read more about why [here](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack)).

This applies to all the PRs you've made to Friends of Flarum extensions. Feel free to PR to a Turkish language pack with these translations, but I'll be closing thee PRs.

Thank you!

**Comment by tolgaaaltas** [comment]
You made me sad. :( Have any guide for language packs for FoF? I'm really like your extensions and want to help Turkish users. How can i bundled all extensions translate files in one? Thank you very very much for everything.

**Comment by datitisev** [comment]
@tolgaaaltas You might want to PR to https://github.com/Madraka/lang-turkish.

And you don't need to bundle all locale files into one, you can have separate files in a language pack. So instead of being called `tr.yml`, it'd be called `fof-formatting.yml`, and so on.

**Comment by tolgaaaltas** [comment]
Got it! Thank you very very much again! You are very kind.

**Pull request closed without merging**
